import { chromium } from 'playwright';
// Прогон интерфейса в браузере: ведущий + 4 команды, скриншоты всех шагов в out/ui/.
// Запуск: npm run ui-smoke   (нужен собранный web/dist и Google Chrome)
import { spawn } from 'node:child_process';
import { mkdirSync, rmSync } from 'node:fs';
const S = process.argv[2] ?? 'out/ui';
mkdirSync(S + '/shots', { recursive: true });
for (const f of ['ui.sqlite', 'ui.sqlite-wal', 'ui.sqlite-shm']) rmSync(`${S}/${f}`, { force: true });
const PORT = 18999;
const env = { ...process.env, PORT: String(PORT), DB_PATH: S + '/ui.sqlite', ADMIN_PASSWORD: 'p', HOST: '127.0.0.1' };
const srv = spawn(process.execPath, ['--import', 'tsx', 'server/src/main.ts'], { env, stdio: 'inherit' });
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
for (let i = 0; i < 60; i++) { try { if ((await fetch(`http://127.0.0.1:${PORT}/api/health`)).ok) break; } catch {} await sleep(200); }
const B = `http://127.0.0.1:${PORT}`;
const browser = await chromium.launch({ channel: 'chrome' });
const fail = async (e: unknown) => { console.error('UI-SMOKE УПАЛ:', e); srv.kill('SIGTERM'); await browser.close(); process.exit(1); };
process.on('unhandledRejection', fail);
process.on('uncaughtException', fail);
const errors: string[] = [];
const mk = async () => { const c = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const p = await c.newPage(); p.setDefaultTimeout(15000); p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => m.type() === 'error' && errors.push(m.text())); return p; };
const admin = await mk();
await admin.goto(B + '/admin');
await admin.fill('input[type=password]', 'p');
await admin.click('button:has-text("Войти")');
await admin.click('button:has-text("Создать игру")');
await admin.waitForSelector('.hero-pin');
const pin = (await admin.textContent('.hero-pin'))!.replace(/\s/g, '');
const teams = [];
for (const n of ['Альфа', 'Бета', 'Гамма', 'Дельта']) {
  const p = await mk();
  await p.goto(B + '/');
  await p.fill('#pin', pin); await p.fill('#nm', n);
  await p.click('button:has-text("Войти в игру")');
  await p.waitForSelector('text=в игре');
  teams.push(p);
}
await sleep(500);
await admin.screenshot({ path: S + '/shots/01-admin-lobby.png', fullPage: true });
await teams[0].screenshot({ path: S + '/shots/02-team-lobby.png' });
await admin.click('button:has-text("Старт игры")');
await admin.click('.modal button:has-text("Да")');
const t = teams[0];
await t.waitForSelector('text=Мини-диагностика');
await t.screenshot({ path: S + '/shots/03-city.png', fullPage: true });
await t.reload(); await t.waitForSelector('text=Мини-диагностика');
const ins = t.locator('.card').filter({ hasText: 'Мини-диагностика' }).locator('input');
const vals = ['Старение', 'Автоматизация', 'Удалёнка', '', 'Инвестиции', 'Миграция', '', 'Коворкинг', '', 'Отток', 'Износ', 'Бюджет'];
for (let i = 0; i < vals.length; i++) if (vals[i]) await ins.nth(i).fill(vals[i]);
await sleep(2500);
await t.reload(); await t.waitForSelector('text=Мини-диагностика');
const restored = await ins.nth(0).inputValue();
console.log('restored after reload:', restored);
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Матрица 2×2');
const mi = t.locator('input.t, textarea.t');
const mv = ['Темп автоматизации', 'быстрый', 'медленный', 'определяет занятость', 'Климат', 'жёсткий', 'мягкий', 'определяет расходы'];
for (let i = 0; i < mv.length; i++) await mi.nth(i).fill(mv[i]);
await sleep(2000);
await t.screenshot({ path: S + '/shots/04-matrix.png', fullPage: true });
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Четыре сценария');
const ti = t.locator('.q input'), ta = t.locator('.q textarea');
for (let i = 0; i < 4; i++) { await ti.nth(i).fill(`Сценарий-${i + 1}`); await ta.nth(i).fill('Город быстро меняется под давлением роботизации. Жители уезжают в мегаполисы ради работы. Бюджет теряет налоговую базу каждый год.'); }
await sleep(2000);
await t.screenshot({ path: S + '/shots/05-scenarios.png', fullPage: true });
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=распределите 100');
const card = (c: string) => t.locator('.measure').filter({ has: t.locator(`.code:text-is("${c}")`) });
await card('M4').locator('button:has-text("Полная")').click();
await card('M13').locator('button:has-text("Условная")').click();
await card('M2').locator('button:has-text("Условная")').click();
await sleep(500);
for (const c of ['M4', 'M13', 'M2']) await card(c).locator('.mark').first().click();
await card('M13').locator('input.t').fill('Два ливня за сезон');
await card('M2').locator('input.t').fill('Сокращение на заводе');
await sleep(1500);
await t.screenshot({ path: S + '/shots/06-budget.png', fullPage: false });
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('.flip.open'); await sleep(1300);
await t.screenshot({ path: S + '/shots/07-joker-neg.png', fullPage: true });
await admin.click('button:has-text("Подробнее") >> nth=0');
await sleep(400);
await admin.screenshot({ path: S + '/shots/08-admin-detail.png' });
await admin.click('.drawer button:has-text("Закрыть")');
await admin.screenshot({ path: S + '/shots/09-admin-overview.png', fullPage: true });
await t.click('button:has-text("К корректировке")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Корректировка 1');
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('.flip.open'); await sleep(1300);
await t.screenshot({ path: S + '/shots/10-joker-pos.png', fullPage: true });
if (await t.locator('.choice').count()) await t.locator('.choice input').first().check({ force: true });
await t.locator('button:has-text("Использовать"), button:has-text("Понятно")').first().click({ timeout: 10000 });
await t.waitForSelector('text=Корректировка 2');
await t.click('button:has-text("Готово")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Закрытие бюджета');
const dec = t.locator('.measure');
for (let i = 0; i < await dec.count(); i++) { await dec.nth(i).locator('button').first().click(); await dec.nth(i).locator('textarea').fill('Триггер сработал в двух сценариях из четырёх.'); }
await sleep(1500);
await t.screenshot({ path: S + '/shots/11-closing.png', fullPage: true });
await t.click('button:has-text("Закрыть бюджет")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Защита решения');
const di = t.locator('input.t, textarea.t');
const dv = ['Сине-зелёная инфраструктура', 'Переподготовка', 'Резерв', 'Паводок — дорогой без подготовки.', 'Опционы дешевле ошибок.'];
for (let i = 0; i < dv.length; i++) await di.nth(i).fill(dv[i]);
await sleep(2000);
await t.click('button:has-text("Завершить")'); await t.click('.modal button:has-text("Перейти")');
await t.waitForSelector('text=Игра завершена');
await t.screenshot({ path: S + '/shots/12-done.png' });
await admin.click('button:has-text("Оценивание")');
await admin.screenshot({ path: S + '/shots/13-grades.png', fullPage: true });
console.log(errors.length ? 'ОШИБКИ В КОНСОЛИ:\n' + errors.join('\n') : `Ошибок в консоли нет. Скриншоты: ${S}/shots`);
if (errors.length) process.exitCode = 1;
await browser.close(); srv.kill('SIGTERM');
